//! Validated domain identifiers.
//!
//! Identifiers are inputs: core never generates one (CONTEXT I13; core
//! contract invariant 9). Constructors validate shape and return a
//! normalized error category the caller can act on. The external bead
//! form is `ABACUS-<suffix>`; the lowercase provider form never crosses
//! the work facade (ADR-0001 §3), so core knows only the external form.

use core::fmt;

/// Distinct identifier-validation failures (core contract: normalized
/// error categories).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IdError {
    Empty,
    TooLong,
    MissingPrefix,
    InvalidCharacter,
    InvalidStructure,
}

const MAX_ID_LEN: usize = 64;

/// External bead identifier: `ABACUS-` plus one or more dot-separated
/// lowercase alphanumeric segments (`ABACUS-hpg`, `ABACUS-hpg.1`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BeadId(String);

pub const BEAD_ID_PREFIX: &str = "ABACUS-";

impl BeadId {
    pub fn new(raw: &str) -> Result<Self, IdError> {
        if raw.is_empty() {
            return Err(IdError::Empty);
        }
        if raw.len() > MAX_ID_LEN {
            return Err(IdError::TooLong);
        }
        let suffix = raw
            .strip_prefix(BEAD_ID_PREFIX)
            .ok_or(IdError::MissingPrefix)?;
        if suffix.is_empty() {
            return Err(IdError::InvalidStructure);
        }
        for segment in suffix.split('.') {
            if segment.is_empty() {
                return Err(IdError::InvalidStructure);
            }
            if !segment
                .bytes()
                .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit())
            {
                return Err(IdError::InvalidCharacter);
            }
        }
        Ok(Self(raw.to_owned()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// The identifier without its `ABACUS-` prefix.
    pub fn suffix(&self) -> &str {
        &self.0[BEAD_ID_PREFIX.len()..]
    }
}

impl fmt::Display for BeadId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Shared shape rule for opaque generated identifiers: nonempty,
/// bounded, lowercase alphanumeric plus hyphen, starting alphanumeric.
fn validate_opaque(raw: &str) -> Result<(), IdError> {
    if raw.is_empty() {
        return Err(IdError::Empty);
    }
    if raw.len() > MAX_ID_LEN {
        return Err(IdError::TooLong);
    }
    if !raw
        .bytes()
        .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
    {
        return Err(IdError::InvalidCharacter);
    }
    let first = raw.as_bytes()[0];
    if !(first.is_ascii_lowercase() || first.is_ascii_digit()) {
        return Err(IdError::InvalidStructure);
    }
    Ok(())
}

macro_rules! opaque_id {
    ($(#[$doc:meta])* $name:ident) => {
        $(#[$doc])*
        #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(String);

        impl $name {
            pub fn new(raw: &str) -> Result<Self, IdError> {
                validate_opaque(raw)?;
                Ok(Self(raw.to_owned()))
            }

            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(&self.0)
            }
        }
    };
}

opaque_id! {
    /// Concrete agent identity recorded on every decision (CONTEXT I17).
    ActorId
}
opaque_id! {
    /// Durable Assignment identity, generated by the composer.
    AssignmentId
}
opaque_id! {
    /// Durable Attempt identity, generated by the composer.
    AttemptId
}
opaque_id! {
    /// Named profile from role-card frontmatter (CONTEXT I16).
    ProfileName
}
opaque_id! {
    /// Durable Signal identity, generated by the composer; the
    /// idempotency key for appends (core contract: idempotently appended).
    SignalId
}
opaque_id! {
    /// ABACUS operation/idempotency identity carried by every decision-
    /// gated mutation (architecture §2/§6 saga; work-contract
    /// idempotency rules). Committed with the authorizing decision and
    /// required by the provider mutation it projects.
    OperationId
}
opaque_id! {
    /// Immutable Handoff identity: what Accept/Reject decisions bind to.
    HandoffId
}
opaque_id! {
    /// Credential identity: names a bearer credential whose plaintext
    /// never crosses this seam — only its digest does (ADR-0003).
    CredentialId
}

/// Namespaced capability identifier, `module:verb` (core contract:
/// capabilities use validated namespaced IDs; descriptors are declared
/// by owning modules and supplied via the composition-root registry).
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct CapabilityId(String);

impl CapabilityId {
    pub fn new(raw: &str) -> Result<Self, IdError> {
        if raw.is_empty() {
            return Err(IdError::Empty);
        }
        if raw.len() > MAX_ID_LEN {
            return Err(IdError::TooLong);
        }
        let Some((module, verb)) = raw.split_once(':') else {
            return Err(IdError::InvalidStructure);
        };
        for (part, allow_underscore) in [(module, false), (verb, true)] {
            if part.is_empty() {
                return Err(IdError::InvalidStructure);
            }
            if !part.bytes().all(|b| {
                b.is_ascii_lowercase()
                    || b.is_ascii_digit()
                    || b == b'-'
                    || (allow_underscore && b == b'_')
            }) {
                return Err(IdError::InvalidCharacter);
            }
            if !part.as_bytes()[0].is_ascii_lowercase() {
                return Err(IdError::InvalidStructure);
            }
        }
        Ok(Self(raw.to_owned()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for CapabilityId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bead_id_valid_forms() {
        for raw in [
            "ABACUS-hpg",
            "ABACUS-9nh",
            "ABACUS-hpg.1",
            "ABACUS-9nh.11",
            "ABACUS-a.b.c",
        ] {
            let id = BeadId::new(raw).unwrap();
            assert_eq!(id.as_str(), raw);
            assert_eq!(format!("{id}"), raw);
        }
        assert_eq!(BeadId::new("ABACUS-hpg.1").unwrap().suffix(), "hpg.1");
    }

    #[test]
    fn bead_id_invalid_forms() {
        let cases = [
            ("", IdError::Empty),
            ("abacus-hpg", IdError::MissingPrefix),
            ("ABACUS_hpg", IdError::MissingPrefix),
            ("hpg", IdError::MissingPrefix),
            ("ABACUS-", IdError::InvalidStructure),
            ("ABACUS-hpg.", IdError::InvalidStructure),
            ("ABACUS-.1", IdError::InvalidStructure),
            ("ABACUS-hpg..1", IdError::InvalidStructure),
            ("ABACUS-HPG", IdError::InvalidCharacter),
            ("ABACUS-hpg_1", IdError::InvalidCharacter),
            ("ABACUS-hpg-1", IdError::InvalidCharacter),
            ("ABACUS-hpg 1", IdError::InvalidCharacter),
        ];
        for (raw, expected) in cases {
            assert_eq!(BeadId::new(raw), Err(expected), "input {raw:?}");
        }
        let long = format!("ABACUS-{}", "a".repeat(MAX_ID_LEN));
        assert_eq!(BeadId::new(&long), Err(IdError::TooLong));
    }

    #[test]
    fn capability_id_forms() {
        assert!(CapabilityId::new("state:assign").is_ok());
        assert!(CapabilityId::new("work:select").is_ok());
        assert!(CapabilityId::new("state:decide_handoff").is_ok());
        assert!(CapabilityId::new("runtime:observe").is_ok());

        assert_eq!(CapabilityId::new(""), Err(IdError::Empty));
        assert_eq!(CapabilityId::new("assign"), Err(IdError::InvalidStructure));
        assert_eq!(CapabilityId::new(":assign"), Err(IdError::InvalidStructure));
        assert_eq!(CapabilityId::new("state:"), Err(IdError::InvalidStructure));
        assert_eq!(
            CapabilityId::new("state:Assign"),
            Err(IdError::InvalidCharacter)
        );
        assert_eq!(
            CapabilityId::new("state:-assign"),
            Err(IdError::InvalidStructure)
        );
        assert_eq!(
            CapabilityId::new("st_ate:assign"),
            Err(IdError::InvalidCharacter)
        );
        assert_eq!(
            CapabilityId::new("state:as sign"),
            Err(IdError::InvalidCharacter)
        );
    }

    #[test]
    fn opaque_id_valid_and_invalid() {
        assert!(ActorId::new("claude-1").is_ok());
        assert!(AssignmentId::new("asg-01f8").is_ok());
        assert!(AttemptId::new("att-01f8-2").is_ok());
        assert!(ProfileName::new("delivery-manager").is_ok());

        assert_eq!(ActorId::new(""), Err(IdError::Empty));
        assert_eq!(ActorId::new("-lead"), Err(IdError::InvalidStructure));
        assert_eq!(ActorId::new("Claude"), Err(IdError::InvalidCharacter));
        assert_eq!(ActorId::new("cl aude"), Err(IdError::InvalidCharacter));
        assert_eq!(
            ActorId::new(&"a".repeat(MAX_ID_LEN + 1)),
            Err(IdError::TooLong)
        );
    }
}
